In [48]:
import pandas as pd
df=pd.read_csv("house_price.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [37]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [40]:
x=df.iloc[:,1:].values
x

array([[7420, 4, 2, ..., 2, 'yes', 'furnished'],
       [8960, 4, 4, ..., 3, 'no', 'furnished'],
       [9960, 3, 2, ..., 2, 'yes', 'semi-furnished'],
       ...,
       [3620, 2, 1, ..., 0, 'no', 'unfurnished'],
       [2910, 3, 1, ..., 0, 'no', 'furnished'],
       [3850, 3, 1, ..., 0, 'no', 'unfurnished']], dtype=object)

In [41]:


from sklearn.preprocessing import LabelEncoder
en1=LabelEncoder()
x[:,4]=en1.fit_transform(x[:,4])
en2=LabelEncoder()
x[:,5]=en2.fit_transform(x[:,5])
en3=LabelEncoder()
x[:,6]=en3.fit_transform(x[:,6])
en4=LabelEncoder()
x[:,7]=en4.fit_transform(x[:,7])
en5=LabelEncoder()
x[:,8]=en5.fit_transform(x[:,8])
en6=LabelEncoder()
x[:,10]=en6.fit_transform(x[:,10])
en7=LabelEncoder()
x[:,11]=en7.fit_transform(x[:,11])
x

array([[7420, 4, 2, ..., 2, 1, 0],
       [8960, 4, 4, ..., 3, 0, 0],
       [9960, 3, 2, ..., 2, 1, 1],
       ...,
       [3620, 2, 1, ..., 0, 0, 2],
       [2910, 3, 1, ..., 0, 0, 0],
       [3850, 3, 1, ..., 0, 0, 2]], dtype=object)

In [42]:
y=df.iloc[:,0].values
y

array([13300000, 12250000, 12250000, 12215000, 11410000, 10850000,
       10150000, 10150000,  9870000,  9800000,  9800000,  9681000,
        9310000,  9240000,  9240000,  9100000,  9100000,  8960000,
        8890000,  8855000,  8750000,  8680000,  8645000,  8645000,
        8575000,  8540000,  8463000,  8400000,  8400000,  8400000,
        8400000,  8400000,  8295000,  8190000,  8120000,  8080940,
        8043000,  7980000,  7962500,  7910000,  7875000,  7840000,
        7700000,  7700000,  7560000,  7560000,  7525000,  7490000,
        7455000,  7420000,  7420000,  7420000,  7350000,  7350000,
        7350000,  7350000,  7343000,  7245000,  7210000,  7210000,
        7140000,  7070000,  7070000,  7035000,  7000000,  6930000,
        6930000,  6895000,  6860000,  6790000,  6790000,  6755000,
        6720000,  6685000,  6650000,  6650000,  6650000,  6650000,
        6650000,  6650000,  6629000,  6615000,  6615000,  6580000,
        6510000,  6510000,  6510000,  6475000,  6475000,  6440000,
        6440000,  6419000,  6405000,  6300000,  6300000,  6300000,
        6300000,  6300000,  6293000,  6265000,  6230000,  6230000,
        6195000,  6195000,  6195000,  6160000,  6160000,  6125000,
        6107500,  6090000,  6090000,  6090000,  6083000,  6083000,
        6020000,  6020000,  6020000,  5950000,  5950000,  5950000,
        5950000,  5950000,  5950000,  5950000,  5950000,  5943000,
        5880000,  5880000,  5873000,  5873000,  5866000,  5810000,
        5810000,  5810000,  5803000,  5775000,  5740000,  5740000,
        5740000,  5740000,  5740000,  5652500,  5600000,  5600000,
        5600000,  5600000,  5600000,  5600000,  5600000,  5600000,
        5600000,  5565000,  5565000,  5530000,  5530000,  5530000,
        5523000,  5495000,  5495000,  5460000,  5460000,  5460000,
        5460000,  5425000,  5390000,  5383000,  5320000,  5285000,
        5250000,  5250000,  5250000,  5250000,  5250000,  5250000,
        5250000,  5250000,  5250000,  5243000,  5229000,  5215000,
        5215000,  5215000,  5145000,  5145000,  5110000,  5110000,
        5110000,  5110000,  5075000,  5040000,  5040000,  5040000,
        5040000,  5033000,  5005000,  4970000,  4970000,  4956000,
        4935000,  4907000,  4900000,  4900000,  4900000,  4900000,
        4900000,  4900000,  4900000,  4900000,  4900000,  4900000,
        4900000,  4900000,  4893000,  4893000,  4865000,  4830000,
        4830000,  4830000,  4830000,  4795000,  4795000,  4767000,
        4760000,  4760000,  4760000,  4753000,  4690000,  4690000,
        4690000,  4690000,  4690000,  4690000,  4655000,  4620000,
        4620000,  4620000,  4620000,  4620000,  4613000,  4585000,
        4585000,  4550000,  4550000,  4550000,  4550000,  4550000,
        4550000,  4550000,  4543000,  4543000,  4515000,  4515000,
        4515000,  4515000,  4480000,  4480000,  4480000,  4480000,
        4480000,  4473000,  4473000,  4473000,  4445000,  4410000,
        4410000,  4403000,  4403000,  4403000,  4382000,  4375000,
        4340000,  4340000,  4340000,  4340000,  4340000,  4319000,
        4305000,  4305000,  4277000,  4270000,  4270000,  4270000,
        4270000,  4270000,  4270000,  4235000,  4235000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4200000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4200000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4193000,  4193000,
        4165000,  4165000,  4165000,  4130000,  4130000,  4123000,
        4098500,  4095000,  4095000,  4095000,  4060000,  4060000,
        4060000,  4060000,  4060000,  4025000,  4025000,  4025000,
        4007500,  4007500,  3990000,  3990000,  3990000,  3990000,
        3990000,  3920000,  3920000,  3920000,  3920000,  3920000,
        3920000,  3920000,  3885000,  3885000,  3850000,  3850000,
        3850000,  3850000,  3850000,  3850000,  3850000,  3836000,
        3815000,  3780000,  3780000,  3780000,  3780000,  3780000,
        3780000,  3773000,  3773000,  3773000,  3745000,  3710000,
        3710000,  3710000,  3710000,  3710000,  3703000,  3703000,
        3675000,  3675000,  3675000,  3675000,  3640000,  3640000,
        3640000,  3640000,  3640000,  3640000,  3640000,  3640000,
        3640000,  3633000,  3605000,  3605000,  3570000,  3570000,
        3570000,  3570000,  3535000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3500000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3500000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3493000,  3465000,  3465000,  3465000,
        3430000,  3430000,  3430000,  3430000,  3430000,  3430000,
        3423000,  3395000,  3395000,  3395000,  3360000,  3360000,
        3360000,  3360000,  3360000,  3360000,  3360000,  3360000,
        3353000,  3332000,  3325000,  3325000,  3290000,  3290000,
        3290000,  3290000,  3290000,  3290000,  3290000,  3290000,
        3255000,  3255000,  3234000,  3220000,  3220000,  3220000,
        3220000,  3150000,  3150000,  3150000,  3150000,  3150000,
        3150000,  3150000,  3150000,  3150000,  3143000,  3129000,
        3118850,  3115000,  3115000,  3115000,  3087000,  3080000,
        3080000,  3080000,  3080000,  3045000,  3010000,  3010000,
        3010000,  3010000,  3010000,  3010000,  3010000,  3003000,
        2975000,  2961000,  2940000,  2940000,  2940000,  2940000,
        2940000,  2940000,  2940000,  2940000,  2870000,  2870000,
        2870000,  2870000,  2852500,  2835000,  2835000,  2835000,
        2800000,  2800000,  2730000,  2730000,  2695000,  2660000,
        2660000,  2660000,  2660000,  2660000,  2660000,  2660000,
        2653000,  2653000,  2604000,  2590000,  2590000,  2590000,
        2520000,  2520000,  2520000,  2485000,  2485000,  2450000,
        2450000,  2450000,  2450000,  2450000,  2450000,  2408000,
        2380000,  2380000,  2380000,  2345000,  2310000,  2275000,
        2275000,  2275000,  2240000,  2233000,  2135000,  2100000,
        2100000,  2100000,  1960000,  1890000,  1890000,  1855000,
        1820000,  1767150,  1750000,  1750000,  1750000])

In [43]:
   from sklearn.model_selection import train_test_split
   x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

   from sklearn.preprocessing import StandardScaler
   sc = StandardScaler()
   x_train = sc.fit_transform(x_train)
   x_test = sc.transform(x_test)

In [44]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [45]:
y_pred=model.predict(x_test)
y_pred

array([ 4019080.69890148,  6258021.76856396,  4392719.13411049,
        7335082.21688188,  2892857.56615676,  7084655.57701773,
        3258634.73504732,  3196499.16068632,  3520106.01134942,
        8359610.28845462,  6646926.36096855,  3788844.63269237,
        3734072.96467982,  4616010.40973201,  3946124.94405791,
        2023177.46846872,  3975554.48783028,  3624716.96500889,
        3210282.7421617 ,  4668411.38105794,  5893719.66376512,
        6415683.83807235,  4657036.55831934,  2704096.11205269,
        5356909.86181448,  5740682.56798043,  5337586.47961081,
        5444859.96648234,  5702144.57144376,  5865872.30432731,
        3307327.30668416,  6299491.02684294,  7123479.95544319,
        2960326.86653053,  4424323.1948382 ,  5125081.85591294,
        4947693.93115736,  3629027.81981124,  2975421.52734787,
        3975089.54021922,  8106313.95534001,  5014658.87529548,
        6469749.69804857,  3566139.31348661,  3868652.86219466,
        6344993.74699856,  4482572.73153155,  2740240.08968071,
        4105384.15298297,  6518557.36176521,  3976558.93952635,
        7056307.68945585,  2586714.16696759,  2947687.80114419,
        3553624.39318114,  5151386.47910423,  7171548.10937834,
        4052242.7088535 ,  2884254.74264867,  4379165.55939616,
        6066225.12442539,  6751773.91534439,  3382551.41414113,
        7251896.59353496,  2681431.47017137,  5138914.78197422,
        6685740.04693818,  2619223.85247951,  3824989.41251459,
        4995902.78242919,  4352358.99961471,  7264572.3528292 ,
        5150347.40449782,  5947769.21201797,  4086573.0979757 ,
        4549426.52941344,  2958392.04612463,  7660252.98149766,
        2656282.61262028,  3679497.40060294,  4352358.99961471,
        5981887.99426367,  5132525.06975503,  5458725.16176888,
        3822006.6426444 ,  4128176.81504508,  4698794.75914508,
        5027920.21505869,  3913610.13040527,  4296868.64305712,
        3290316.24497528,  5880621.00664525,  3150060.86792803,
        3668445.62490135,  4539382.03106224, 10575679.21780641,
        2971774.44221853,  7093653.99925703,  4418061.77112388,
        4577913.0785326 ,  6542179.32091917,  3322929.37680989,
        4620712.65928558,  3364236.6234678 ,  7400967.88555255,
        5138942.23888226,  4058811.42233282,  4972825.57184573,
        6367950.02587763])

In [46]:
y_test

array([ 4585000,  6083000,  4007500,  6930000,  2940000,  6195000,
        3535000,  2940000,  3500000,  7980000,  6755000,  3990000,
        3150000,  3290000,  4130000,  2660000,  4410000,  3710000,
        3360000,  4270000,  5005000,  5383000,  6440000,  1890000,
        6125000,  5460000,  5803000,  4620000,  5530000,  5950000,
        4305000,  3640000,  5250000,  3325000,  3703000,  4753000,
        9100000,  3500000,  3150000,  4270000,  8960000,  4060000,
        5740000,  3129000,  3633000,  7560000,  4620000,  3290000,
        4165000,  6650000,  4165000,  4690000,  3150000,  3850000,
        3290000,  5075000,  6510000,  5740000,  3780000,  4795000,
        4900000,  5460000,  3500000,  7525000,  2835000,  5495000,
        8680000,  4200000,  4200000,  4900000,  3332000,  6195000,
        4098500,  6650000,  3885000,  4620000,  1960000,  6440000,
        1750000,  3605000,  3290000,  4970000,  4613000,  3850000,
        3500000,  6107500,  3780000,  4900000,  3570000,  4340000,
        3500000,  6300000,  3395000,  3815000,  3920000, 12250000,
        3080000,  9310000,  4270000,  3780000,  5600000,  3290000,
        2380000,  5110000,  6650000,  5810000,  4123000,  3080000,
        5530000])

In [47]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print("Mean absolute error=",mean_absolute_error(y_test,y_pred))
mse=mean_squared_error(y_test,y_pred)
rmse=mse**.5
print("Root Mean squared error=",rmse)
from sklearn.metrics import r2_score
print("R2 score =", r2_score(y_test, y_pred))

Mean absolute error= 716583.4396615443
Root Mean squared error= 992996.3765744686
R2 score = 0.6578047592637606